
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

from tkinter import messagebox
from pathlib import Path
import subprocess
# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / "assets" / "frame0"


def check_password():
    entered_password = entry_1.get()
    correct_password = "1414"

    if entered_password == correct_password:
        subprocess.Popen(["python", r"C:\Users\Administrator\Desktop\Interview design\Admin Actions\build\admin.py"])
    else:
        messagebox.showerror("Error", "Incorrect password.")



def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("405x321")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 321,
    width = 405,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
entry_image_1 = PhotoImage(
    file=relative_to_assets("res.png"))
entry_bg_1 = canvas.create_image(
    227.0,
    104.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0,
    font=("Inter Bold", 16 * -1,"bold"),
    show="*"
)
entry_1.place(
    x=141.0,
    y=90.0,
    width=170.0,
    height=24.0
)

canvas.create_text(
    10.0,
    96.0,
    anchor="nw",
    text="PASSWORD :",
    fill="#000000",
    font=("Inter Bold", 16 * -1,"bold")
)

button_image_1 = PhotoImage(
    file=relative_to_assets("sub1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=check_password,
    relief="flat"
)
button_1.place(
    x=116.0,
    y=188.0,
    width=204.0,
    height=60.0
)
window.resizable(False, False)
window.mainloop()
